#!/usr/bin/env bash

help() {
  echo "Welcome to wslgBox!"
  echo "wslgBox is licensed under GPL-3.0."
  echo "--Help--"
  echo "--help, -h: shows this help screen"
  echo "--install, -i: installs kde for you"
  echo "--troubleshooting, -t: shows troubleshooting steps"
  echo "--update, -u: updates wslgbox"
  echo "--installcommunity, -ic: installs community files (ALLOWS CODE EXECUTION)"
  exit
}

update() {
  echo "Testing internet connection..."
  wget -q --spider http://github.com
  if [ $? -eq 0 ]; then
    echo "Checking latest version..."
    GIT_VERSION="$(curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/version 2> /dev/null)"
    if [[ "$GIT_VERSION" == "$VERSION" ]]; then
      echo "You are already up to date."
    else
      read -p "The latest release is $GIT_VERSION. Press any key to update, or ^C to cancel. "
      if test -f "$HOME/.config/wslgbox/enabledcommsloading"; then
        echo "Updating community files..."
        curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/community_de_support/comfunc > $HOME/.config/wslgbox/comfunc
        curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/community_de_support/comif > $HOME/.config/wslgbox/comif
        curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/community_de_support/cominst > $HOME/.config/wslgbox/cominst
      fi
      curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/wslgbox > wslgbox
      chmod +x wslgbox
      echo "Updated!"
      sleep 1s
      bash wslgbox
    fi
    exit
  else
    echo "You are not connected to the internet!"
  fi
  exit
}

enablecommunity() {
  read -p "This could be dangerous, as it allows for potentially unwanted code execution. Press any key if you are sure. I AM NOT RESPONSIBLE FOR ANY DAMAGES. "
  read -p "Are you positive? "
  read -p "This is your last chance to cancel. Are you sure you want to do this? "
  echo Waiting 5 seconds before continuing...
  sleep 5s
  echo Enabling...
  echo 1 > $HOME/.config/wslgbox/enabledcommsloading
  echo Enabled. Checking for updates...
  update
}

VERSION=1.1.4

bold=$(tput bold)
normal=$(tput sgr0)

mkdir $HOME/.config 2> /dev/null
mkdir $HOME/.config/wslgbox 2> /dev/null

clear
echo "               _       ____              "
echo "              | |     |  _ \             "
echo " __      _____| | __ _| |_) | _____  __  "
echo " \ \ /\ / / __| |/ _. |  _ < / _ \ \/ /  "
echo "  \ V  V /\__ \ | (_| | |_) | (_) >  <   "
echo "   \_/\_/ |___/_|\__. |____/ \___/_/\_\  "
echo "                  __/ |                  "
echo "                 |___/               v$VERSION    " # i'm really sorry this isnt center :<
echo "----------------"
echo "wslgBox v$VERSION by creamy-dev"
echo "de's on wslg"
echo "----------------"

## Reference
# 0 = openbox
# 1 = kde

if [[ "$@" == *"--help"* ]]; then
  help
  exit
fi

if [[ "$@" == *"-h"* ]]; then
  help
  exit
fi

if [[ "$@" == *"-t"* ]]; then
  curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/troubleshooting.txt
  exit
fi

if [[ "$@" == *"--update"* ]]; then
  update
fi

if [[ "$@" == *"-u"* ]]; then
  update
fi

if [[ "$@" == *"--installcommunity"* ]]; then
  enablecommunity
fi

if [[ "$@" == *"-ic"* ]]; then
  enablecommunity
fi

if [[ "$@" == *"--troubleshooting"* ]]; then
  curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/troubleshooting.txt
  exit
fi

if test -f "$HOME/.config/wslgbox/noautoupdates"; then echo 1 > /dev/null; else
  wget -q --spider http://github.com
  if [ $? -eq 0 ]; then
    GIT_VERSION="$(curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/version 2> /dev/null)"
    if [[ "$GIT_VERSION" != "$VERSION" ]]; then
      read -p "The latest release is $GIT_VERSION. Press any key to update, or ^C to cancel. "
      curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/wslgbox > wslgbox
      if test -f "$HOME/.config/wslgbox/enabledcommsloading"; then
        echo "Updating community files..." > /dev/null
        curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/community_de_support/comfunc > $HOME/.config/wslgbox/comfunc
        curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/community_de_support/comif > $HOME/.config/wslgbox/comif
        curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/community_de_support/cominst > $HOME/.config/wslgbox/cominst
      fi
      chmod +x wslgbox
      echo "Updated!"
      sleep 1s
      bash wslgbox
      exit
    fi
  fi
fi

if test -f "$HOME/.config/wslgbox/agreement"; then echo 1 > /dev/null; else
  echo "Welcome, to wslgBox! (licensed under GPL-3.0)"
  echo "This software is ${bold}AS-IS${normal}, you may use this at your own risk. I am not responsible if I break anything."
  echo "This WILL modify wslg services that may be restored later, on next boot. This will also wipe /tmp, on each script run."
  echo "I do not guarantee anything will be restored, or that anything will work."
  read -p "Press any key if you agree to these terms. "
  echo 1 > $HOME/.config/wslgbox/agreement
  echo 1 > $HOME/.config/wslgbox/de
  echo "----------------"
fi

dashdashinstall() {
  NAME="$(awk -F= '$1=="NAME" { print $2 ;}' /etc/os-release)"
  if [[ "$(cat $HOME/.config/wslgbox/de)" == 1 ]]; then
    if [[ "$NAME" == '"Debian GNU/Linux"' ]]; then
      echo "IMPORTANT:"
      echo "We WILL need to wipe ~/.config,"
      echo "And we WILL need to migrate to debian testing due to KDE gui bugs, in the debian stable version. (${bold}THIS WILL WIPE /etc/apt/sources.list${normal})"
      echo "You should back up all your important files."
      read -p "Press any key if you agree to these modifications to your computer, or CTRL+C to exit. "
      echo "deb http://deb.debian.org/debian testing main" | sudo tee /etc/apt/sources.list 2> /dev/null
      echo "deb http://deb.debian.org/debian testing-updates main" | sudo tee -a /etc/apt/sources.list 2> /dev/null
      echo "deb http://security.debian.org/debian-security testing-security main" | sudo tee -a /etc/apt/sources.list 2> /dev/null
      echo "deb http://ftp.debian.org/debian testing-backports main" | sudo tee -a /etc/apt/sources.list 2> /dev/null
      sudo apt update
      sudo apt upgrade -y
      sudo apt autoremove -y
      sudo apt install kde-plasma-desktop xwayland kwin-x11 dbus-x11 -y
      echo "Done!"
    elif [[ "$NAME" == '"Ubuntu"' ]]; then
      sudo apt update
      sudo apt install kubuntu-desktop xwayland kwin-x11 dbus-x11 -y
      echo "Done!"
    else echo "Unsupported distrobution."; fi
    exit
  fi

  if test -f "$HOME/.config/wslgbox/enabledcommsloading"; then
    source $HOME/.config/wslgbox/cominst
  fi
}

prepare() {
  sudo systemctl stop wslg-xwayland.service
  sudo systemctl stop wslg-xwayland.socket
  sudo rm -rf /tmp/*
  killall Xwayland
  killall openbox
}

start_openbox() {
  Xwayland &
  sleep 0.5s
  GDK_BACKEND=x11 openbox &
  sleep 0.5s
  cat ~/.config/openbox/autostart | bash
  while :; do
    sleep 2s
  done
}

start_kde() {
  Xwayland &
  sleep 0.5s
  GDK_BACKEND=x11 startplasma-x11 &
  sleep 0.5s
  kwin --replace
}

if test -f "$HOME/.config/wslgbox/enabledcommsloading"; then
  source $HOME/.config/wslgbox/comfunc
fi

if [[ "$@" == *"--install"* ]]; then
  dashdashinstall
fi

if [[ "$@" == *"-i"* ]]; then
  dashdashinstall
fi

echo "Preparing..."
prepare
echo "Starting..."
file_data="$(cat $HOME/.config/wslgbox/de)"

if [ $file_data == 0 ]; then
  start_openbox
  exit
fi

if [ $file_data == 1 ]; then
  start_kde
  exit
fi

if test -f "$HOME/.config/wslgbox/enabledcommsloading"; then
  source $HOME/.config/wslgbox/comif
fi
