#!/usr/bin/env bash

VERSION=1.1.0

bold=$(tput bold)
normal=$(tput sgr0)

mkdir $HOME/.config/wslgbox 2> /dev/null

clear
echo "               _       ____              "
echo "              | |     |  _ \             "
echo " __      _____| | __ _| |_) | _____  __  "
echo " \ \ /\ / / __| |/ _. |  _ < / _ \ \/ /  "
echo "  \ V  V /\__ \ | (_| | |_) | (_) >  <   "
echo "   \_/\_/ |___/_|\__. |____/ \___/_/\_\  "
echo "                  __/ |                  "
echo "                 |___/               v$VERSION    " # i'm really sorry this isnt center :<
echo "----------------"
echo "wslgBox v$VERSION by creamy#1337"
echo "openbox X11-like on wslg"
echo "----------------"

## Reference
# 0 = openbox
# 1 = kde

if test -f "$HOME/.config/wslgbox/agreement"; then echo 1 > /dev/null; else
    echo "Welcome, to wslgBox!"
    echo "This software is ${bold}AS-IS${normal}, you may use this at your own risk. I am not responsible if I break anything."
    echo "This WILL modify wslg services that may be restored later, on next boot. This will also wipe /tmp, on each script run."
    echo "I do not guarantee anything will be restored, or that anything will work."
    read -p "Press any key if you agree to these terms. "
    echo 1 > $HOME/.config/wslgbox/agreement
    echo 1 > $HOME/.config/wslgbox/de
    echo "----------------"
fi

prepare() {
    sudo systemctl stop wslg-xwayland.service
    sudo systemctl stop wslg-xwayland.socket
    sudo rm -rf /tmp/*
    killall Xwayland
    killall openbox
}

start_openbox() {
    Xwayland &
    sleep 0.5s
    GDK_BACKEND=x11 openbox &
    sleep 0.5s
    cat ~/.config/openbox/autostart | bash
    while :; do
        sleep 2s
    done
}

start_kde() {
    Xwayland &
    sleep 0.5s
    startplasma-x11 &
    sleep 0.5s
    kwin --replace
}

echo "Preparing..."
prepare
echo "Starting..."
file_data="$(cat $HOME/.config/wslgbox/de)"
if [ $file_data == 0 ]; then
  start_openbox
elif [ $file_data == 1 ]; then
  start_kde
fi
