#!/usr/bin/env bash

help() {
  echo "Welcome to wslgBox!"
  echo "wslgBox is licensed under GPL-3.0."
  echo "--Help--"
  echo "--help, -h: shows this help screen"
  echo "--install, -i: installs kde for you"
  echo "--troubleshooting, -t: shows troubleshooting steps"
  echo "--update, -u: updates wslgbox"
  exit
}

update() {
  echo "Checking latest version..."
  GIT_VERSION="$(curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/version 2> /dev/null)"
  if [[ "$GIT_VERSION" == "$VERSION" ]]; then
    echo "You are already up to date."
  else
    read -p "The latest release is $GIT_VERSION. Do you want to update? "
    curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/wslgbox > wslgbox
    chmod +x wslgbox
    echo "Updated!"
    sleep 1s
    bash wslgbox
  fi
  exit
}

VERSION=1.1.0

bold=$(tput bold)
normal=$(tput sgr0)

mkdir $HOME/.config/wslgbox 2> /dev/null

clear
echo "               _       ____              "
echo "              | |     |  _ \             "
echo " __      _____| | __ _| |_) | _____  __  "
echo " \ \ /\ / / __| |/ _. |  _ < / _ \ \/ /  "
echo "  \ V  V /\__ \ | (_| | |_) | (_) >  <   "
echo "   \_/\_/ |___/_|\__. |____/ \___/_/\_\  "
echo "                  __/ |                  "
echo "                 |___/               v$VERSION    " # i'm really sorry this isnt center :<
echo "----------------"
echo "wslgBox v$VERSION by @creamy-dev"
echo "de's on wslg"
echo "----------------"

## Reference
# 0 = openbox
# 1 = kde

if [[ "$@" == *"--help"* ]]; then
  help
  exit
fi

if [[ "$@" == *"-h"* ]]; then
  help
  exit
fi

if [[ "$@" == *"-t"* ]]; then
  curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/troubleshooting.txt
  exit
fi

if [[ "$@" == *"--update"* ]]; then
  update
fi

if [[ "$@" == *"-u"* ]]; then
  update
fi

if [[ "$@" == *"--troubleshooting"* ]]; then
  curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/troubleshooting.txt
  exit
fi

GIT_VERSION="$(curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/version 2> /dev/null)"
if [[ "$GIT_VERSION" == "$VERSION" ]]; then
  echo 1 > /dev/null
else
  read -p "The latest release is $GIT_VERSION. Do you want to update? "
  curl https://raw.githubusercontent.com/creamy-dev/wslgBox/main/wslgbox > wslgbox
  chmod +x wslgbox
  echo "Updated!"
  sleep 1s
  bash wslgbox
fi
exit

if test -f "$HOME/.config/wslgbox/agreement"; then echo 1 > /dev/null; else
  echo "Welcome, to wslgBox! (licensed under GPL-3.0)"
  echo "This software is ${bold}AS-IS${normal}, you may use this at your own risk. I am not responsible if I break anything."
  echo "This WILL modify wslg services that may be restored later, on next boot. This will also wipe /tmp, on each script run."
  echo "I do not guarantee anything will be restored, or that anything will work."
  read -p "Press any key if you agree to these terms. "
  echo 1 > $HOME/.config/wslgbox/agreement
  echo 1 > $HOME/.config/wslgbox/de
  echo "----------------"
fi

dashdashinstall() {
  NAME="$(awk -F= '$1=="NAME" { print $2 ;}' /etc/os-release)"
  if [[ "$NAME" == '"Debian GNU/Linux"' ]]; then
    echo "IMPORTANT:"
    echo "We WILL need to wipe ~/.config,"
    echo "And we WILL need to migrate to debian testing due to KDE gui bugs, in the debian stable version. (${bold}THIS WILL WIPE /etc/apt/sources.list${normal})"
    echo "You should back up all your important files."
    read -p "Press any key if you agree to these modifications to your computer, or CTRL+C to exit. "
    echo "deb http://deb.debian.org/debian testing main" | sudo tee /etc/apt/sources.list 2> /dev/null
    echo "deb http://deb.debian.org/debian testing-updates main" | sudo tee -a /etc/apt/sources.list 2> /dev/null
    echo "deb http://security.debian.org/debian-security testing-security main" | sudo tee -a /etc/apt/sources.list 2> /dev/null
    echo "deb http://ftp.debian.org/debian testing-backports main" | sudo tee -a /etc/apt/sources.list 2> /dev/null
    sudo apt update
    sudo apt upgrade -y
    sudo apt autoremove -y
    sudo apt install kde-plasma-desktop xwayland kwin-x11 dbus-x11 -y
    echo "Done!"
  elif [[ "$NAME" == '"Ubuntu"' ]]; then
    sudo apt update 
    sudo apt install kubuntu-desktop xwayland kwin-x11 dbus-x11 -y
    echo "Done!"
  else echo "Unsupported distrobution."; fi
  exit
}

prepare() {
  sudo systemctl stop wslg-xwayland.service
  sudo systemctl stop wslg-xwayland.socket
  sudo rm -rf /tmp/*
  killall Xwayland
  killall openbox
}

start_openbox() {
  Xwayland &
  sleep 0.5s
  GDK_BACKEND=x11 openbox &
  sleep 0.5s
  cat ~/.config/openbox/autostart | bash
  while :; do
    sleep 2s
  done
}

start_kde() {
  Xwayland &
  sleep 0.5s
  startplasma-x11 &
  sleep 0.5s
  kwin --replace
}

if [[ "$@" == *"--install"* ]]; then
  dashdashinstall
fi

if [[ "$@" == *"-i"* ]]; then
  dashdashinstall
fi

echo "Preparing..."
prepare
echo "Starting..."
file_data="$(cat $HOME/.config/wslgbox/de)"
if [ $file_data == 0 ]; then
  start_openbox
elif [ $file_data == 1 ]; then
  start_kde
fi
